- mybatis-spring-boot-autoconfigure/src/main/java/org/mybatis/spring/boot/autoconfigure/MybatisAutoConfiguration.java
- mybatis-spring-boot-autoconfigure/src/main/java/org/mybatis/spring/boot/autoconfigure/MybatisProperties.java
- mybatis-spring-boot-autoconfigure/src/test/java/org/mybatis/spring/boot/autoconfigure/MybatisAutoConfigurationTest.java
- mybatis-spring-boot-autoconfigure/src/test/resources/mybatis-config.xml
In currently implementation, executor type of `SqlSessionTemplate` is fixed to `SIMPLE` by default.
However, i think that it should be change to use `Configuration#getDefaultExecutorType()` of injected `SqlSessionFactory` .
What do you think ?
> Change to use executorType of SqlSessionFactory instead of SIMPLE by default

- mybatis-spring-boot-autoconfigure/src/test/java/org/mybatis/spring/boot/autoconfigure/MybatisAutoConfigurationTest.java
I've modified assertion for specifying at the same time with 'configuration' and 'configLocation' because an error message is not fixed.
> Modify a assertion method for specifying with 'configuration' and 'configLocation'

- mybatis-spring-boot-autoconfigure/src/main/java/org/mybatis/spring/boot/autoconfigure/MybatisAutoConfiguration.java
- mybatis-spring-boot-autoconfigure/src/test/java/org/mybatis/spring/boot/autoconfigure/MybatisAutoConfigurationTest.java
When `check-config-location` is `true` and `config-location` not present, following error occurred.
```
...
Caused by: java.lang.IllegalArgumentException: Location must not be null
at org.springframework.util.Assert.notNull(Assert.java:115)
at org.springframework.core.io.DefaultResourceLoader.getResource(DefaultResourceLoader.java:90)
at org.springframework.context.support.GenericApplicationContext.getResource(GenericApplicationContext.java:211)
at org.mybatis.spring.boot.autoconfigure.MybatisAutoConfiguration.checkConfigFileExists(MybatisAutoConfiguration.java:98)
...
```
I think this case should skip a check.
> Add condition for checking presence of a config file

- mybatis-spring-boot-autoconfigure/src/main/java/org/mybatis/spring/boot/autoconfigure/MybatisProperties.java
I've modified to export metadata of the `Configuration`.
Please review.
See http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#configuration-metadata-nested-properties.
> Configuration properties export to spring-configuration-metadata.json

- mybatis-spring-boot-autoconfigure/src/main/java/org/mybatis/spring/boot/autoconfigure/MybatisAutoConfiguration.java
I've polished some codes.
* Removed unnecessary `+` operation
* Added `isDebugEnabled`
* Renamed local variable
Please review.
Thanks.
> Polishing some codes

- mybatis-spring-boot-autoconfigure/pom.xml
- mybatis-spring-boot-samples/mybatis-spring-boot-sample-annotation/pom.xml
- mybatis-spring-boot-samples/mybatis-spring-boot-sample-xml/pom.xml
- mybatis-spring-boot-starter/pom.xml
- mybatis-spring-boot-starter/src/main/resources/META-INF/spring.provides
- pom.xml
I've fixed gh-102.
@eddumelendez @emacarron @hazendaz , please review.
> Improve the dependency structure for autoconfigure and starter

- mybatis-spring-boot-samples/mybatis-spring-boot-sample-annotation/pom.xml
- mybatis-spring-boot-samples/mybatis-spring-boot-sample-xml/pom.xml
- mybatis-spring-boot-samples/pom.xml
I've improved to mange ognl and javassist using dependency management on sample applications.
> Fix to manage ognl and javassist using dependency management element on parent pom

- mybatis-spring-boot-autoconfigure/src/main/java/org/mybatis/spring/boot/autoconfigure/MybatisAutoConfiguration.java
- mybatis-spring-boot-autoconfigure/src/main/java/org/mybatis/spring/boot/autoconfigure/MybatisProperties.java
- mybatis-spring-boot-autoconfigure/src/test/java/org/mybatis/spring/boot/autoconfigure/MybatisAutoConfigurationTest.java
I've added `configurationProperties` on `MybatisProperties` for customizing a global property.
`mybatis-config.xml`:
``` xml
<properties>
<property name="key" value="value1" />
</properties>
```
Can override a defined property or define a new property  at `application.properties` as follows:
``` properties
mybatis.configuration-properties.key=value2
```
These properties can use as placeholder(`${...}` format) in `mybatis-config.xml` and SQL statement.  (In this case, `${key}` will replace to `value2`)
Please review.
> Add configurationProperties on MybatisProperties

- pom.xml
I've fixed gh-127 as workaround.
Please review this.
Configuration values in `MANIFEST.MF` are same excludes `Bnd-LastModified`, `Implementation-Build-Date` and `Tool`.
> Note that maven-bundle-plugin 3.x does not support JDK 6.
> Update to maven-bundle-plugin 3.2.0

- mybatis-spring-boot-samples/mybatis-spring-boot-sample-annotation/pom.xml
- mybatis-spring-boot-samples/mybatis-spring-boot-sample-xml/pom.xml
- pom.xml
The annotation sample pom is incorrectly formatted.
Our standard is 2 spaces but it was using tab characters.
The problem with it not being an executable jar was we weren't telling the maven spring boot plugin to repackage. This change will make the jar executable.
> Fixes #128

- pom.xml
See gh-236
I've added the `junit-vintage-engine on maven-surefire-plugin` for execution JUnit 4 tests.
> Add junit-vintage-engine on maven-surefire-plugin

- mybatis-spring-boot-autoconfigure/pom.xml
- mybatis-spring-boot-autoconfigure/src/test/java/org/mybatis/spring/boot/autoconfigure/AdditionalConfigurationMetadataTest.java
- mybatis-spring-boot-autoconfigure/src/test/java/org/mybatis/spring/boot/autoconfigure/MybatisAutoConfigurationTest.java
- mybatis-spring-boot-autoconfigure/src/test/java/org/mybatis/spring/boot/autoconfigure/MybatisPropertiesTest.java
- mybatis-spring-boot-samples/mybatis-spring-boot-sample-annotation/pom.xml
- mybatis-spring-boot-samples/mybatis-spring-boot-sample-annotation/src/test/java/extensions/CaptureSystemOutput.java
- mybatis-spring-boot-samples/mybatis-spring-boot-sample-annotation/src/test/java/sample/mybatis/SampleMybatisApplicationTest.java
- mybatis-spring-boot-samples/mybatis-spring-boot-sample-annotation/src/test/java/sample/mybatis/mapper/CityMapperTest.java
- mybatis-spring-boot-samples/mybatis-spring-boot-sample-xml/pom.xml
- mybatis-spring-boot-samples/mybatis-spring-boot-sample-xml/src/test/java/extensions/CaptureSystemOutput.java
- mybatis-spring-boot-samples/mybatis-spring-boot-sample-xml/src/test/java/sample/mybatis/SampleMybatisApplicationTest.java
- mybatis-spring-boot-samples/mybatis-spring-boot-sample-xml/src/test/java/sample/mybatis/dao/CityDaoTest.java
- mybatis-spring-boot-samples/mybatis-spring-boot-sample-xml/src/test/java/sample/mybatis/mapper/HotelMapperTest.java
- mybatis-spring-boot-starter-test/pom.xml
- mybatis-spring-boot-test-autoconfigure/pom.xml
- mybatis-spring-boot-test-autoconfigure/src/test/java/org/mybatis/spring/boot/test/autoconfigure/MybatisTestCustomFilterIntegrationTest.java
- mybatis-spring-boot-test-autoconfigure/src/test/java/org/mybatis/spring/boot/test/autoconfigure/MybatisTestIntegrationTest.java
- pom.xml
option 1 in going to junit 5 is to truck on through and get there with this disabling the 3.
option 2 is to revert the original changes I made as spring was a little more covert on how many times junit 4 was showing up which I've corrected here.
option 3 would be someone on the team that can figure out the bigger failure case and get it applied as well in this commit set.  The console out tests are not really that important and I've got an open issue with the class (2 of them) that were added here as it seems to work in general use cases but not spring boot which is using logback.  That might be a hint for figuring that out.
> Junit 5 - take 2 - Tests are all running now

- mybatis-spring-boot-samples/mybatis-spring-boot-sample-annotation/src/main/java/sample/mybatis/mapper/CityMapper.java
- mybatis-spring-boot-samples/mybatis-spring-boot-sample-xml/src/main/resources/sample/mybatis/mapper/CityMapper.xml
- mybatis-spring-boot-samples/mybatis-spring-boot-sample-xml/src/main/resources/sample/mybatis/mapper/HotelMapper.xml
To follow best practices the wildcards (*) was removed from queries and replaced with proper and complete list of columns.
> Improved SQL queries for annotation and XML samples

- mybatis-spring-boot-autoconfigure/src/main/java/org/mybatis/spring/boot/autoconfigure/SpringBootVFS.java
- mybatis-spring-boot-autoconfigure/src/test/java/org/mybatis/spring/boot/autoconfigure/MybatisAutoConfigurationTest.java
> Fix resources scanning bug on SpringBootVFS

- mybatis-spring-boot-starter-test/src/main/resources/META-INF/spring.provides
- mybatis-spring-boot-starter/src/main/resources/META-INF/spring.provides
This PR removes the `spring.provides` files.
See https://github.com/spring-projects/spring-boot/issues/12435
> Remove spring.provides files

- mybatis-spring-boot-autoconfigure/src/main/java/org/mybatis/spring/boot/autoconfigure/MybatisAutoConfiguration.java
- mybatis-spring-boot-autoconfigure/src/site/xdoc/index.xml.vm
- mybatis-spring-boot-autoconfigure/src/test/java/org/mybatis/spring/boot/autoconfigure/MybatisAutoConfigurationTest.java
> Detect a TypeHandler from DI Container

- mybatis-spring-boot-autoconfigure/pom.xml
- mybatis-spring-boot-autoconfigure/src/main/java/org/mybatis/spring/boot/autoconfigure/MybatisAutoConfiguration.java
- mybatis-spring-boot-autoconfigure/src/main/java/org/mybatis/spring/boot/autoconfigure/MybatisLanguageDriverAutoConfiguration.java
- mybatis-spring-boot-autoconfigure/src/main/java/org/mybatis/spring/boot/autoconfigure/MybatisProperties.java
- mybatis-spring-boot-autoconfigure/src/main/resources/META-INF/spring.factories
- mybatis-spring-boot-autoconfigure/src/site/xdoc/index.xml.vm
- mybatis-spring-boot-autoconfigure/src/test/java/org/mybatis/spring/boot/autoconfigure/MybatisAutoConfigurationTest.java
- mybatis-spring-boot-autoconfigure/src/test/java/org/mybatis/spring/boot/autoconfigure/MybatisLanguageDriverAutoConfigurationTest.java
- pom.xml
> Support auto-configure LanguageDriver provided by MyBatis's sub module

- mybatis-spring-boot-test-autoconfigure/src/main/java/org/mybatis/spring/boot/test/autoconfigure/MybatisTest.java
- mybatis-spring-boot-test-autoconfigure/src/main/java/org/mybatis/spring/boot/test/autoconfigure/MybatisTestContextBootstrapper.java
- mybatis-spring-boot-test-autoconfigure/src/test/java/org/mybatis/spring/boot/test/autoconfigure/MybatisTestIntegrationTest.java
> Add 'properties' attribute on MybatisTest annotation

- .travis.yml
- mybatis-spring-boot-autoconfigure/pom.xml
- mybatis-spring-boot-samples/mybatis-spring-boot-sample-annotation/pom.xml
- mybatis-spring-boot-samples/mybatis-spring-boot-sample-freemarker-legacy/pom.xml
- mybatis-spring-boot-samples/mybatis-spring-boot-sample-freemarker/pom.xml
- mybatis-spring-boot-samples/mybatis-spring-boot-sample-groovy/pom.xml
- mybatis-spring-boot-samples/mybatis-spring-boot-sample-kotlin/pom.xml
- mybatis-spring-boot-samples/mybatis-spring-boot-sample-thymeleaf/pom.xml
- mybatis-spring-boot-samples/mybatis-spring-boot-sample-velocity-legacy/pom.xml
- mybatis-spring-boot-samples/mybatis-spring-boot-sample-velocity/pom.xml
- mybatis-spring-boot-samples/mybatis-spring-boot-sample-war/pom.xml
- mybatis-spring-boot-samples/mybatis-spring-boot-sample-web/pom.xml
- mybatis-spring-boot-samples/mybatis-spring-boot-sample-xml/pom.xml
- mybatis-spring-boot-starter-test/pom.xml
- mybatis-spring-boot-test-autoconfigure/pom.xml
- pom.xml
Prevent following warning.
```
Dec 10, 2019 4:05:00 PM org.junit.platform.launcher.core.DefaultLauncher handleThrowable
WARNING: TestEngine with ID 'junit-vintage' failed to discover tests
java.lang.NoClassDefFoundError: junit/runner/Version
at org.junit.vintage.engine.JUnit4VersionCheck.checkSupported(JUnit4VersionCheck.java:32)
at org.junit.vintage.engine.VintageTestEngine.discover(VintageTestEngine.java:61)
at org.junit.platform.launcher.core.DefaultLauncher.discoverEngineRoot(DefaultLauncher.java:168)
at org.junit.platform.launcher.core.DefaultLauncher.discoverRoot(DefaultLauncher.java:155)
at org.junit.platform.launcher.core.DefaultLauncher.discover(DefaultLauncher.java:120)
at org.apache.maven.surefire.junitplatform.TestPlanScannerFilter.accept(TestPlanScannerFilter.java:56)
at …
```
> Prevent warning of junit-vintage on spring-boot 2.2.x

- mybatis-spring-boot-autoconfigure/src/site/markdown/index.md
`VelocityLanguageDriver` was written `ThymeleafLanguageDriver`
> fix heading in docs

- mybatis-spring-boot-samples/mybatis-spring-boot-sample-war/pom.xml
See gh-607
The Spring Boot 3.0 requires the Tomcat 10.
> Change configuration for allowing override the tomcat major version on tests

- mybatis-spring-boot-autoconfigure/src/test/java/org/mybatis/spring/boot/autoconfigure/AdditionalConfigurationMetadataTest.java
**Problem:**
A test method with many individual assertions stops being executed on the first failed assertion, which prevents the remaining ones' execution.
**Solution:**
Using JUnit's grouped assertions feature, all assertions are executed, and all failures will be reported together. In this refactoring, no original assertion was changed and assertions were grouped by property.
**Result:**
_Before:_
```
// assert for mybatis.configuration.default-enum-type-handler
{
Map<String, Object> element = properties.get(1);
assertThat(element.get("sourceType")).isEqualTo("org.apache.ibatis.session.Configuration");
assertThat(element.get("defaultValue")).isEqualTo("org.apache.ibatis.type.EnumTypeHandler");
assertThat(element.get("name")).isEqualTo("mybatis.configuration.default-enum-type-handler"); …
```
> Improved execution of grouped assertions

- mybatis-spring-boot-autoconfigure/src/test/java/org/mybatis/spring/boot/autoconfigure/MybatisAutoConfigurationTest.java
> Add test for ordering interceptor

- mybatis-spring-boot-autoconfigure/src/site/zh/markdown/index.md
I don't notice that MyBatis-Spring has a translated doc before. Now I update the link to the zh doc for being friendly.
> Update the link in zh doc

- mybatis-spring-boot-autoconfigure/src/main/java/org/mybatis/spring/boot/autoconfigure/SpringBootVFS.java
- mybatis-spring-boot-autoconfigure/src/test/java/org/mybatis/spring/boot/autoconfigure/MybatisAutoConfigurationTest.java
- mybatis-spring-boot-autoconfigure/src/test/java/org/mybatis/spring/boot/autoconfigure/バリューオブジェクト/シティー.java
- mybatis-spring-boot-autoconfigure/src/test/resources/mybatis-config2.xml
- pom.xml
> Support non ascii characters of resource path on SpringBootVFS

- mybatis-spring-boot-autoconfigure/src/test/java/org/mybatis/spring/boot/autoconfigure/MybatisAutoConfigurationTest.java
Will fix https://github.com/kazuki43zoo/mybatis-spring-boot-dev-compatibility-checker/actions/runs/2853810869.
> Change assertion on detecting configuration file does not exits for spring-boot 3

- mybatis-spring-boot-autoconfigure/src/main/java/org/mybatis/spring/boot/autoconfigure/MybatisAutoConfiguration.java
- mybatis-spring-boot-autoconfigure/src/main/java/org/mybatis/spring/boot/autoconfigure/MybatisLanguageDriverAutoConfiguration.java
> Set to proxyBeanMethods=false on Configuration class

- pom.xml
was mixing meta data with source/target at 17 but release at 8, surprising it worked to compile...
> [pom] Fix java release version: must be 17

- mybatis-spring-boot-autoconfigure/src/main/java/org/mybatis/spring/boot/autoconfigure/MybatisProperties.java
I want to open `CoreConfiguration#applyTo`.
My application needs to connect to multiple MySQL instances, so I need to configure multiple datasource/mybatis.
(Because I am sharding MySQL and accessing replica for some queries).
Therefore, I was using mybatis-spring-starter with customize.
(To be more specific, I did not use `MybatisAutoConfiguration`, but wrote the equivalent configuration code myself.)
`CoreConfiguration` is new in mybatis-spring-boot-starter-3.x.
I tried to modify our code to mimic [this method](https://github.com/mybatis/spring-boot-starter/blob/3bffc1fbe0c88a62d5f8df04c4726e030055c130/mybatis-spring-boot-autoconfigure/src/main/java/org/mybatis/spring/boot/autoconfigure/MybatisAutoConfiguration.java#L138), but the `CoreConfiguration#applyTo` is NOT public.
Currently, we …
> Open `CoreConfiguration#applyTo`

- mybatis-spring-boot-autoconfigure/src/main/java/org/mybatis/spring/boot/autoconfigure/SpringBootVFS.java
Fixes gh-542
* Use the returned instance from ClassUtils#getDefaultClassLoader()
* Can customize to use any class loader instance using Supplier
> Enable the thread context class loader in SpringBootVFS

- .github/workflows/ci.yaml
- .github/workflows/coveralls.yaml
- .github/workflows/sonar.yaml
- .github/workflows/sonatype.yaml
- .github/workflows/support.yaml
- mybatis-spring-boot-samples/mybatis-spring-boot-sample-web/src/test/java/sample/mybatis/web/SampleMybatisWithMockBeanApplicationTest.java
> Add test with @MockBean

- .github/workflows/site.yaml
To use, simply merge code up to either tip of master or to tag you which to have the site release on.  Note, the later comment there up to the tag will actually be skipped in current form, assuming we want to do it that way, we will need to remove the check on the commit message.
> [GHA] Add 'site.yaml' to release the site

- mybatis-spring-boot-autoconfigure/src/main/java/org/mybatis/spring/boot/autoconfigure/MybatisProperties.java
- mybatis-spring-boot-autoconfigure/src/test/java/org/mybatis/spring/boot/autoconfigure/MybatisPropertiesTest.java
- pom.xml
* multipleResultSetsEnabled deprecated
* https://github.com/mybatis/mybatis-3/pull/3238
> Update to MyBatis 3.5.17

- mybatis-spring-boot-starter-test/pom.xml
- mybatis-spring-boot-starter-test/src/main/java/org/mybatis/spring/boot/starter/test/package-info.java
- mybatis-spring-boot-starter/pom.xml
- mybatis-spring-boot-starter/src/main/java/org/mybatis/spring/boot/starter/package-info.java
I add `package-info.java` for generating javadoc and source jar file at starter projects. The `maven.javadoc.failOnError` option need for generate the javadoc jar file with only `package-info.java` file.
**NOTE:** We need to generate javadoc and source jar files for deploying to Maven Central repository.
> Add package-info.java for generating javadoc and source jar file
