README.md

Update version to 1.0.1 at README.md

---

README.md

I've updated the `README.md` for 1.0.2 release.

Update to 1.0.2 in README.md

---

mybatis-spring-boot-autoconfigure/src/main/java/org/mybatis/spring/boot/autoconfigure/MybatisAutoConfiguration.java
mybatis-spring-boot-autoconfigure/src/main/java/org/mybatis/spring/boot/autoconfigure/MybatisProperties.java
mybatis-spring-boot-autoconfigure/src/test/java/org/mybatis/spring/boot/autoconfigure/MybatisAutoConfigurationTest.java
mybatis-spring-boot-autoconfigure/src/test/resources/mybatis-config.xml

I've fixed to support https://github.com/mybatis/spring/pull/108 on Spring Boot.
This PR move from #25 .
Please review.

Allow direct configuration without config file

---

mybatis-spring-boot-autoconfigure/src/site/xdoc/index.xml.vm

I've improved doc for #47 .
Please review.

Improve doc for direct configuration without config file (related with gh-47)

---

mybatis-spring-boot-autoconfigure/src/main/java/org/mybatis/spring/boot/autoconfigure/MybatisProperties.java

I've fixed small mistakes in javadoc.
Please review.

config -> configLocation in javadoc

---

mybatis-spring-boot-autoconfigure/src/test/java/org/mybatis/spring/boot/autoconfigure/MybatisAutoConfigurationTest.java

I've improved tests.
* `mybatis.config` -> `mybatis.config-location`
* Add test for `mybatis.config` (compatibility with 1.0.x)
Please review.

Improve test cases for MybatisAutoConfigurationTest

---

mybatis-spring-boot-samples/mybatis-spring-boot-sample-xml/src/main/resources/application.properties

I've modified to use `mybatis.config-location`.
Please review.

mybatis.config -> mybatis.config-location in sample

---

mybatis-spring-boot-autoconfigure/src/main/java/org/mybatis/spring/boot/autoconfigure/MybatisProperties.java

I've polished some code at `MybatisProperties`.
Please review.
Thanks.

Polishing the MybatisProperties

---

mybatis-spring-boot-autoconfigure/src/main/java/org/mybatis/spring/boot/autoconfigure/SpringBootVFS.java

I've improved code of `SpringBootVFS`.
Please review.
Thanks.

Improve logic of SpringBootVFS

---

mybatis-spring-boot-autoconfigure/src/site/xdoc/index.xml.vm

Add description for check-config-location in docs

---

mybatis-spring-boot-samples/mybatis-spring-boot-sample-annotation/src/main/java/sample/mybatis/domain/City.java
mybatis-spring-boot-samples/mybatis-spring-boot-sample-annotation/src/test/java/sample/mybatis/SampleMybatisApplicationTest.java
mybatis-spring-boot-samples/mybatis-spring-boot-sample-xml/src/main/java/sample/mybatis/domain/City.java
mybatis-spring-boot-samples/mybatis-spring-boot-sample-xml/src/main/java/sample/mybatis/domain/Hotel.java
mybatis-spring-boot-samples/mybatis-spring-boot-sample-xml/src/test/java/sample/mybatis/SampleMybatisApplicationTest.java

I've polished classes of sample application.

Polishing sample applications

---

pom.xml

Upgrade to Spring Boot 1.3.4

---

mybatis-spring-boot-autoconfigure/src/site/xdoc/index.xml.vm

It's my first contribution to github. Hope I do it properly.

fix "href" of 2nd eaxmple

---

pom.xml

Upgrade to MyBatis 3.4.1

---

pom.xml

I've updated to latest Spring Boot version.
Please review.

Upgrade to Spring Boot 1.3.6.RELEASE

---

mybatis-spring-boot-autoconfigure/src/main/java/org/mybatis/spring/boot/autoconfigure/MybatisAutoConfiguration.java

I've modified to use the `Logger` of slf4j.
Please review #66 .

Modify to use slf4j api instead of commons logging api #66

---

pom.xml

Upgrade to Spring Boot 1.4.1.RELEASE

---

mybatis-spring-boot-autoconfigure/src/site/xdoc/index.xml.vm

I've added example for configuration using `application.properties`.
Please review.

Add example for configuration using application.properties

---

mybatis-spring-boot-autoconfigure/src/main/java/org/mybatis/spring/boot/autoconfigure/MybatisAutoConfiguration.java

I've polished some codes on `MybatisAutoConfiguration`.
Please review.

Polishing MybatisAutoConfiguration

---

pom.xml

Spring Boot 1.4.2 has been released.

Upgrade to Spring Boot 1.4.2.RELEASE

---

mybatis-spring-boot-autoconfigure/src/site/xdoc/index.xml.vm

I've polished some sentence and added example for yaml file configuration in reference document.

Polishing reference document

---

mybatis-spring-boot-autoconfigure/src/main/java/org/mybatis/spring/boot/autoconfigure/MybatisProperties.java
mybatis-spring-boot-autoconfigure/src/site/xdoc/index.xml.vm

I've updated reference doc (related with gh-101).

Add explanation for 'mybatis.configuration-properties' in reference doc

---

mybatis-spring-boot-autoconfigure/src/test/java/org/mybatis/spring/boot/autoconfigure/MybatisAutoConfigurationTest.java

Add tests for custom SqlSessionFactory and SqlSessionTemplate 

---

mybatis-spring-boot-samples/mybatis-spring-boot-sample-annotation/src/main/resources/application.properties
mybatis-spring-boot-samples/mybatis-spring-boot-sample-xml/src/main/resources/application.properties

I've added `classpath:` prefix. see gh-121.

Add classpath: prefix gh-121

---

mybatis-spring-boot-samples/mybatis-spring-boot-sample-annotation/src/main/java/sample/mybatis/SampleMapperApplication.java
mybatis-spring-boot-samples/mybatis-spring-boot-sample-xml/src/main/java/sample/mybatis/SampleXmlApplication.java
mybatis-spring-boot-samples/mybatis-spring-boot-sample-xml/src/main/java/sample/mybatis/dao/CityDao.java

Improve to use constructor injection

---

mybatis-spring-boot-autoconfigure/src/main/java/org/mybatis/spring/boot/autoconfigure/ConfigurationCustomizer.java
mybatis-spring-boot-autoconfigure/src/main/java/org/mybatis/spring/boot/autoconfigure/MybatisAutoConfiguration.java
mybatis-spring-boot-autoconfigure/src/test/java/org/mybatis/spring/boot/autoconfigure/MybatisAutoConfigurationTest.java

I've fixed the gh-132.
Please review this.

Add the callback interface that can be customized a Configuration

---

mybatis-spring-boot-samples/mybatis-spring-boot-sample-annotation/src/main/java/sample/mybatis/SampleMybatisApplication.java
mybatis-spring-boot-samples/mybatis-spring-boot-sample-annotation/src/test/java/sample/mybatis/mapper/CityMapperTest.java
mybatis-spring-boot-samples/mybatis-spring-boot-sample-annotation/src/test/java/sample/mybatis/mapper/MapperTestApplication.java
mybatis-spring-boot-samples/mybatis-spring-boot-sample-xml/src/main/java/sample/mybatis/SampleMybatisApplication.java
mybatis-spring-boot-samples/mybatis-spring-boot-sample-xml/src/test/java/sample/mybatis/dao/CityDaoTest.java
mybatis-spring-boot-samples/mybatis-spring-boot-sample-xml/src/test/java/sample/mybatis/dao/DaoTestApplication.java
mybatis-spring-boot-samples/mybatis-spring-boot-sample-xml/src/test/java/sample/mybatis/mapper/HotelMapperTest.java
mybatis-spring-boot-samples/mybatis-spring-boot-sample-xml/src/test/java/sample/mybatis/mapper/MapperTestApplication.java

See gh-143
* Change class name for Spring Boot Application (`Sample***Application` -> `SampleMybatisApplication`)
* Change class name and package name for test case class using `@MybatisTest`
* Add Spring Boot Application class for testing (`DaoTestApplication` and `MapperTestApplication`) for prevent to run the actual Spring Boot Application (`SampleMybatisApplication`)
* Change bean definition method for `CityDao` (inner java config -> `@Import`)
Please review this.

Polishing test on sample applications

---

mybatis-spring-boot-autoconfigure/src/main/java/org/mybatis/spring/boot/autoconfigure/ConfigurationCustomizer.java
mybatis-spring-boot-autoconfigure/src/main/java/org/mybatis/spring/boot/autoconfigure/MybatisAutoConfiguration.java
mybatis-spring-boot-autoconfigure/src/main/java/org/mybatis/spring/boot/autoconfigure/MybatisProperties.java
mybatis-spring-boot-autoconfigure/src/main/java/org/mybatis/spring/boot/autoconfigure/SpringBootVFS.java
pom.xml

Fixes gh-194
I've changed as follows:
* Add the `@FunctionalInterface` on `ConfigurationCustomizer`
* Use the Lambda expression if possible
* Use the `Optional` if possible
* Change the Java version of maven-compiler-plugin
* Change artifact of "Animal Sniffer Signature"
@mybatis/committers 
Please review this.

Update Java requirement to 8

---

.travis.yml
pom.xml

Support JDK9 on Travis CI

---

mybatis-spring-boot-test-autoconfigure/src/site/xdoc/index.xml.vm

This PR adds a missing Spring Boot version in the document.

Add a missing Spring Boot version in doc

---

mybatis-spring-boot-autoconfigure/src/main/java/org/mybatis/spring/boot/autoconfigure/MybatisAutoConfiguration.java
mybatis-spring-boot-autoconfigure/src/main/java/org/mybatis/spring/boot/autoconfigure/MybatisProperties.java
mybatis-spring-boot-autoconfigure/src/test/java/org/mybatis/spring/boot/autoconfigure/MybatisAutoConfigurationTest.java
mybatis-spring-boot-autoconfigure/src/test/java/org/mybatis/spring/boot/autoconfigure/domain/Domain.java
mybatis-spring-boot-autoconfigure/src/test/java/org/mybatis/spring/boot/autoconfigure/domain/Name.java

Add the typeAliasesSuperType on MybatisProperties

---

.travis.yml

Support JDK10 on Travis CI

---

mybatis-spring-boot-test-autoconfigure/src/site/xdoc/index.xml.vm

This PR replace 
```
dependencies {
compile("org.mybatis.spring.boot:mybatis-spring-boot-starter-test:1.3.2")
}
```
to
```
dependencies {
testCompile("org.mybatis.spring.boot:mybatis-spring-boot-starter-test:1.3.2")
}
```

replace compile with testCompile

---

mybatis-spring-boot-autoconfigure/src/main/java/org/mybatis/spring/boot/autoconfigure/MybatisAutoConfiguration.java

Change to use the InitializingBean instead of @PostConstruct

---

.travis.yml
pom.xml

Support JDK 11 on Travis CI

---

mybatis-spring-boot-autoconfigure/src/test/resources/logback-test.xml

Related with https://github.com/mybatis/spring-boot-starter/pull/286#issuecomment-451996507

Prevent unnecessary log output

---

mybatis-spring-boot-autoconfigure/src/test/resources/logback-test.xml

(cherry picked from commit 738cef4aa1b15022b4969a08316feab79d3ad585)
Related with https://github.com/mybatis/spring-boot-starter/pull/286#issuecomment-451996507

[1.3.x] Prevent unnecessary log output

---

mybatis-spring-boot-autoconfigure/src/main/java/org/mybatis/spring/boot/autoconfigure/MybatisAutoConfiguration.java

Fixes gh-258
(cherry picked from commit f0ba1a3ed11eb2a84c226c1c87aa654c15b5a2b2)
I've backported to 1.3.x.

Change a method for preventing package based mapper scan

---

mybatis-spring-boot-autoconfigure/src/main/java/org/mybatis/spring/boot/autoconfigure/SpringBootVFS.java
mybatis-spring-boot-autoconfigure/src/test/java/org/mybatis/spring/boot/autoconfigure/MybatisAutoConfigurationTest.java

Fix resources scanning bug on SpringBootVFS

---

.travis.yml
pom.xml

Support JKD 12 on Travis CI for 1.3.x

---

mybatis-spring-boot-test-autoconfigure/pom.xml
mybatis-spring-boot-test-autoconfigure/src/main/java/org/mybatis/spring/boot/test/autoconfigure/MybatisTest.java
mybatis-spring-boot-test-autoconfigure/src/site/xdoc/index.xml.vm
mybatis-spring-boot-test-autoconfigure/src/test/java/org/mybatis/spring/boot/test/autoconfigure/MybatisTestCustomFilterIntegrationTest.java
mybatis-spring-boot-test-autoconfigure/src/test/java/org/mybatis/spring/boot/test/autoconfigure/MybatisTestIntegrationTest.java

 Add @ExtendWith(SpringExtension.class) on @mybatistest

---

mybatis-spring-boot-autoconfigure/src/main/java/org/mybatis/spring/boot/autoconfigure/MybatisAutoConfiguration.java
mybatis-spring-boot-autoconfigure/src/main/resources/META-INF/additional-spring-configuration-metadata.json
mybatis-spring-boot-autoconfigure/src/site/xdoc/index.xml.vm
mybatis-spring-boot-autoconfigure/src/test/java/org/mybatis/spring/boot/autoconfigure/AdditionalConfigurationMetadataTest.java
mybatis-spring-boot-autoconfigure/src/test/java/org/mybatis/spring/boot/autoconfigure/MybatisAutoConfigurationTest.java
pom.xml

Support enable/disable lazy Initialization on mapper scanning feature

---

mybatis-spring-boot-autoconfigure/src/main/java/org/mybatis/spring/boot/autoconfigure/MybatisAutoConfiguration.java
mybatis-spring-boot-autoconfigure/src/test/java/com/example/mapper/DateTimeMapper.java
mybatis-spring-boot-autoconfigure/src/test/java/org/mybatis/spring/boot/autoconfigure/MybatisAutoConfigurationTest.java

Add MapperScannerConfigurer as condition to avoid auto scan mapper

---

mybatis-spring-boot-autoconfigure/src/main/java/org/mybatis/spring/boot/autoconfigure/MybatisLanguageDriverAutoConfiguration.java
mybatis-spring-boot-autoconfigure/src/site/xdoc/index.xml.vm
mybatis-spring-boot-autoconfigure/src/test/java/org/mybatis/spring/boot/autoconfigure/MybatisLanguageDriverAutoConfigurationTest.java

Support configuration properties for mybatis-thymeleaf

---

mybatis-spring-boot-autoconfigure/src/main/resources/META-INF/additional-spring-configuration-metadata.json

Deprecate the 'mybatis.configuration.default-scripting-language'

---

mybatis-spring-boot-autoconfigure/src/main/java/org/mybatis/spring/boot/autoconfigure/MybatisLanguageDriverAutoConfiguration.java
mybatis-spring-boot-autoconfigure/src/site/xdoc/index.xml.vm
mybatis-spring-boot-autoconfigure/src/test/java/org/mybatis/spring/boot/autoconfigure/MybatisLanguageDriverAutoConfigurationTest.java
pom.xml

Support configuration properties for mybatis-freemarker

---

mybatis-spring-boot-autoconfigure/src/main/java/org/mybatis/spring/boot/autoconfigure/MybatisLanguageDriverAutoConfiguration.java
mybatis-spring-boot-autoconfigure/src/main/resources/META-INF/additional-spring-configuration-metadata.json
mybatis-spring-boot-autoconfigure/src/site/xdoc/index.xml.vm
mybatis-spring-boot-autoconfigure/src/test/java/org/mybatis/spring/boot/autoconfigure/AdditionalConfigurationMetadataTest.java
mybatis-spring-boot-autoconfigure/src/test/java/org/mybatis/spring/boot/autoconfigure/MybatisLanguageDriverAutoConfigurationTest.java
pom.xml

Support configuration properties for mybatis-velocity

---

mybatis-spring-boot-autoconfigure/src/site/xdoc/index.xml.vm
mybatis-spring-boot-samples/mybatis-spring-boot-sample-kotlin/format.xml
mybatis-spring-boot-samples/mybatis-spring-boot-sample-kotlin/license.txt
mybatis-spring-boot-samples/mybatis-spring-boot-sample-kotlin/pom.xml
mybatis-spring-boot-samples/mybatis-spring-boot-sample-kotlin/src/main/kotlin/sample/mybatis/SampleKotlinApplication.kt
mybatis-spring-boot-samples/mybatis-spring-boot-sample-kotlin/src/main/kotlin/sample/mybatis/domain/City.kt
mybatis-spring-boot-samples/mybatis-spring-boot-sample-kotlin/src/main/kotlin/sample/mybatis/mapper/CityMapper.kt
mybatis-spring-boot-samples/mybatis-spring-boot-sample-kotlin/src/main/resources/application.properties
mybatis-spring-boot-samples/mybatis-spring-boot-sample-kotlin/src/main/resources/data.sql
mybatis-spring-boot-samples/mybatis-spring-boot-sample-kotlin/src/main/resources/schema.sql
mybatis-spring-boot-samples/mybatis-spring-boot-sample-kotlin/src/test/kotlin/extensions/CaptureSystemOutput.java
mybatis-spring-boot-samples/mybatis-spring-boot-sample-kotlin/src/test/kotlin/sample/mybatis/SampleMybatisApplicationMainTest.kt
mybatis-spring-boot-samples/mybatis-spring-boot-sample-kotlin/src/test/kotlin/sample/mybatis/SampleMybatisApplicationTest.kt
mybatis-spring-boot-samples/mybatis-spring-boot-sample-kotlin/src/test/kotlin/sample/mybatis/mapper/CityMapperTest.kt
mybatis-spring-boot-samples/mybatis-spring-boot-sample-kotlin/src/test/kotlin/sample/mybatis/mapper/MapperTestApplication.kt
mybatis-spring-boot-samples/pom.xml
mybatis-spring-boot-test-autoconfigure/src/site/xdoc/index.xml.vm

Add sample for kotlin

---

mybatis-spring-boot-autoconfigure/src/site/xdoc/index.xml.vm
mybatis-spring-boot-samples/mybatis-spring-boot-sample-groovy/format.xml
mybatis-spring-boot-samples/mybatis-spring-boot-sample-groovy/license.txt
mybatis-spring-boot-samples/mybatis-spring-boot-sample-groovy/pom.xml
mybatis-spring-boot-samples/mybatis-spring-boot-sample-groovy/src/main/groovy/sample/mybatis/SampleGroovyApplication.groovy
mybatis-spring-boot-samples/mybatis-spring-boot-sample-groovy/src/main/groovy/sample/mybatis/domain/City.groovy
mybatis-spring-boot-samples/mybatis-spring-boot-sample-groovy/src/main/groovy/sample/mybatis/mapper/CityMapper.groovy
mybatis-spring-boot-samples/mybatis-spring-boot-sample-groovy/src/main/resources/application.properties
mybatis-spring-boot-samples/mybatis-spring-boot-sample-groovy/src/main/resources/data.sql
mybatis-spring-boot-samples/mybatis-spring-boot-sample-groovy/src/main/resources/schema.sql
mybatis-spring-boot-samples/mybatis-spring-boot-sample-groovy/src/test/groovy/extensions/CaptureSystemOutput.groovy
mybatis-spring-boot-samples/mybatis-spring-boot-sample-groovy/src/test/groovy/sample/mybatis/SampleMybatisApplicationMainTest.groovy
mybatis-spring-boot-samples/mybatis-spring-boot-sample-groovy/src/test/groovy/sample/mybatis/SampleMybatisApplicationTest.groovy
mybatis-spring-boot-samples/mybatis-spring-boot-sample-groovy/src/test/groovy/sample/mybatis/mapper/CityMapperTest.groovy
mybatis-spring-boot-samples/mybatis-spring-boot-sample-groovy/src/test/groovy/sample/mybatis/mapper/MapperTestApplication.groovy
mybatis-spring-boot-samples/pom.xml
mybatis-spring-boot-test-autoconfigure/src/site/xdoc/index.xml.vm

Add sample for groovy

---

.travis.yml
pom.xml

Support build using OpenJDK 13 on Travis CI

---

mybatis-spring-boot-autoconfigure/src/site/markdown/index.md
mybatis-spring-boot-samples/mybatis-spring-boot-sample-war/pom.xml
mybatis-spring-boot-samples/mybatis-spring-boot-sample-war/src/main/java/sample/mybatis/SampleWebApplication.java
mybatis-spring-boot-samples/mybatis-spring-boot-sample-war/src/main/java/sample/mybatis/controller/CityRestController.java
mybatis-spring-boot-samples/mybatis-spring-boot-sample-war/src/main/java/sample/mybatis/domain/City.java
mybatis-spring-boot-samples/mybatis-spring-boot-sample-war/src/main/java/sample/mybatis/mapper/CityMapper.java
mybatis-spring-boot-samples/mybatis-spring-boot-sample-war/src/main/resources/application.properties
mybatis-spring-boot-samples/mybatis-spring-boot-sample-war/src/main/resources/data.sql
mybatis-spring-boot-samples/mybatis-spring-boot-sample-war/src/main/resources/schema.sql
mybatis-spring-boot-samples/mybatis-spring-boot-sample-war/src/main/resources/spring.properties
mybatis-spring-boot-samples/mybatis-spring-boot-sample-war/src/test/java/sample/mybatis/SampleMybatisApplicationIT.java
mybatis-spring-boot-samples/mybatis-spring-boot-sample-war/src/test/java/sample/mybatis/SampleMybatisApplicationTest.java
mybatis-spring-boot-samples/mybatis-spring-boot-sample-war/src/test/java/sample/mybatis/mapper/CityMapperTest.java
mybatis-spring-boot-samples/mybatis-spring-boot-sample-war/src/test/java/sample/mybatis/mapper/MapperTestApplication.java
mybatis-spring-boot-samples/mybatis-spring-boot-sample-web/format.xml
mybatis-spring-boot-samples/mybatis-spring-boot-sample-web/license.txt
mybatis-spring-boot-samples/mybatis-spring-boot-sample-web/pom.xml
mybatis-spring-boot-samples/mybatis-spring-boot-sample-web/src/main/java/sample/mybatis/SampleWebApplication.java
mybatis-spring-boot-samples/mybatis-spring-boot-sample-web/src/main/java/sample/mybatis/controller/CityRestController.java
mybatis-spring-boot-samples/mybatis-spring-boot-sample-web/src/main/java/sample/mybatis/domain/City.java
mybatis-spring-boot-samples/mybatis-spring-boot-sample-web/src/main/java/sample/mybatis/mapper/CityMapper.java
mybatis-spring-boot-samples/mybatis-spring-boot-sample-web/src/main/resources/application.properties
mybatis-spring-boot-samples/mybatis-spring-boot-sample-web/src/main/resources/data.sql
mybatis-spring-boot-samples/mybatis-spring-boot-sample-web/src/main/resources/schema.sql
mybatis-spring-boot-samples/mybatis-spring-boot-sample-web/src/test/java/sample/mybatis/SampleMybatisApplicationTest.java
mybatis-spring-boot-samples/mybatis-spring-boot-sample-web/src/test/java/sample/mybatis/mapper/CityMapperTest.java
mybatis-spring-boot-samples/mybatis-spring-boot-sample-web/src/test/java/sample/mybatis/mapper/MapperTestApplication.java
mybatis-spring-boot-samples/pom.xml

Add sample for web env

---

.travis.yml
mybatis-spring-boot-samples/mybatis-spring-boot-sample-groovy/pom.xml
pom.xml

* Upgrade to groovy 3.0.0-rc-1
* Upgrade to Jacoco 0.8.5
Fixes gh-351

Support OpenJDK 14 on Travis CI

---

README.md

fix word misspelling

---

.travis.yml

Prevent a build error on openjdk-ea(openjdk15)

---

pom.xml

Update to mybatis-spring 2.0.5-SNAPSHOT

---

.travis.yml
mybatis-spring-boot-test-autoconfigure/pom.xml
pom.xml

Switch baseline to Spring Boot 2.3

---

mybatis-spring-boot-samples/mybatis-spring-boot-sample-freemarker/src/main/java/sample/mybatis/SampleFreeMarkerApplication.java
mybatis-spring-boot-samples/mybatis-spring-boot-sample-freemarker/src/main/java/sample/mybatis/mapper/CityMapper.java
mybatis-spring-boot-samples/mybatis-spring-boot-sample-freemarker/src/main/resources/application.properties
mybatis-spring-boot-samples/mybatis-spring-boot-sample-freemarker/src/main/resources/mappers/CityMapper-findByCountry.ftl
mybatis-spring-boot-samples/mybatis-spring-boot-sample-freemarker/src/test/java/sample/mybatis/SampleMybatisApplicationMainTest.java
mybatis-spring-boot-samples/mybatis-spring-boot-sample-freemarker/src/test/java/sample/mybatis/SampleMybatisApplicationTest.java
mybatis-spring-boot-samples/mybatis-spring-boot-sample-freemarker/src/test/java/sample/mybatis/mapper/CityMapperTest.java
mybatis-spring-boot-samples/mybatis-spring-boot-sample-thymeleaf/src/main/java/sample/mybatis/SampleThymeleafApplication.java
mybatis-spring-boot-samples/mybatis-spring-boot-sample-thymeleaf/src/main/java/sample/mybatis/mapper/CityMapper.java
mybatis-spring-boot-samples/mybatis-spring-boot-sample-thymeleaf/src/main/resources/application.properties
mybatis-spring-boot-samples/mybatis-spring-boot-sample-thymeleaf/src/main/resources/data.sql
mybatis-spring-boot-samples/mybatis-spring-boot-sample-thymeleaf/src/main/resources/mappers/CityMapper-findByCountry.sql
mybatis-spring-boot-samples/mybatis-spring-boot-sample-thymeleaf/src/test/java/sample/mybatis/SampleMybatisApplicationMainTest.java
mybatis-spring-boot-samples/mybatis-spring-boot-sample-thymeleaf/src/test/java/sample/mybatis/SampleMybatisApplicationTest.java
mybatis-spring-boot-samples/mybatis-spring-boot-sample-thymeleaf/src/test/java/sample/mybatis/mapper/CityMapperTest.java

Add sample(test) using TemplateFilePathProvider

---

.travis.yml
mybatis-spring-boot-samples/run_fatjars.sh

Add tests for Fat Jar(samples) on Travis CI

---

mybatis-spring-boot-autoconfigure/src/main/java/org/mybatis/spring/boot/autoconfigure/MybatisLanguageDriverAutoConfiguration.java

Keep to output configuration properties metadata of thymeleaf (apply workaround)

---

pom.xml

Update mybatis-parent 32-SNAPSHOT for preventing build error on JDK 15

---

.travis.yml

Support CI using Spring Boot 2.3

---

mybatis-spring-boot-autoconfigure/src/site/markdown/index.md
mybatis-spring-boot-test-autoconfigure/src/site/markdown/index.md
pom.xml

Replace the artifact version on index.md at build time

---

README.md
mybatis-spring-boot-autoconfigure/src/site/markdown/index.md
mybatis-spring-boot-test-autoconfigure/src/main/resources/META-INF/spring.factories
mybatis-spring-boot-test-autoconfigure/src/site/markdown/index.md
pom.xml

Switch baseline to Spring Boot 2.5

---

pom.xml

Update to Spring Boot 2.4.6

---

mybatis-spring-boot-samples/mybatis-spring-boot-sample-war/pom.xml

Update Tomcat 9.0.55

---

pom.xml

Switch base line version to Spring Boot 2.6

---

pom.xml

Update mybatis-spring 2.0.7 release version instead of SNAPSHOT

---

pom.xml

Update mybatis-spring 2.1.0-SNAPSHOT

---

mybatis-spring-boot-autoconfigure/src/main/java/org/mybatis/spring/boot/autoconfigure/MybatisAutoConfiguration.java

avoid resolving MapperLocations twice

avoid resolving MapperLocations twice

---

mybatis-spring-boot-autoconfigure/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
mybatis-spring-boot-test-autoconfigure/src/main/resources/META-INF/spring/org.mybatis.spring.boot.test.autoconfigure.AutoConfigureMybatis.imports

Add imports file that define auto configure classes supported by spring-boot 2.7

---

mybatis-spring-boot-samples/mybatis-spring-boot-sample-groovy/pom.xml

Upgrade to groovy 4.0

---

mybatis-spring-boot-autoconfigure/pom.xml
mybatis-spring-boot-autoconfigure/src/main/java/org/mybatis/spring/boot/autoconfigure/MybatisDependsOnDatabaseInitializationDetector.java
mybatis-spring-boot-autoconfigure/src/main/resources/META-INF/spring.factories
mybatis-spring-boot-autoconfigure/src/test/java/org/mybatis/spring/boot/autoconfigure/MybatisAutoConfigurationTest.java
mybatis-spring-boot-autoconfigure/src/test/java/org/mybatis/spring/boot/autoconfigure/MybatisLanguageDriverAutoConfigurationTest.java
mybatis-spring-boot-autoconfigure/src/test/java/org/mybatis/spring/boot/autoconfigure/TestAutoConfigurationPackage.java
mybatis-spring-boot-autoconfigure/src/test/java/org/mybatis/spring/boot/autoconfigure/TestAutoConfigurationPackageRegistrar.java
mybatis-spring-boot-autoconfigure/src/test/resources/db/changelog/db.changelog-city.yaml
mybatis-spring-boot-autoconfigure/src/test/resources/db/changelog/db.changelog-master.yaml
mybatis-spring-boot-autoconfigure/src/test/resources/db/changelog/db.changelog-override.json
mybatis-spring-boot-autoconfigure/src/test/resources/db/changelog/db.changelog-override.sql
mybatis-spring-boot-autoconfigure/src/test/resources/db/changelog/db.changelog-override.xml
mybatis-spring-boot-autoconfigure/src/test/resources/db/migration/V1__init.sql

SqlTemplate depends on flyway/liquibase execution

---

pom.xml

Update the mybatis-spring-boot url address in the pom.xml file

modify http to https

---

.github/workflows/ci.yaml
.github/workflows/coveralls.yaml
.github/workflows/sonar.yaml
.github/workflows/sonatype.yaml
.github/workflows/support.yaml
mybatis-spring-boot-samples/mybatis-spring-boot-sample-kotlin/pom.xml
mybatis-spring-boot-samples/mybatis-spring-boot-sample-war/pom.xml
pom.xml

Apply Spring Boot 3 and mybatis-spring 3 

---

mybatis-spring-boot-autoconfigure/src/main/java/org/mybatis/spring/boot/autoconfigure/SpringBootVFS.java

Support normalize scanned resource path

---

mybatis-spring-boot-autoconfigure/src/main/java/org/mybatis/spring/boot/autoconfigure/MybatisAutoConfiguration.java
mybatis-spring-boot-autoconfigure/src/main/java/org/mybatis/spring/boot/autoconfigure/MybatisProperties.java
mybatis-spring-boot-autoconfigure/src/main/resources/META-INF/additional-spring-configuration-metadata.json
mybatis-spring-boot-autoconfigure/src/test/java/org/mybatis/spring/boot/autoconfigure/AdditionalConfigurationMetadataTest.java
mybatis-spring-boot-autoconfigure/src/test/java/org/mybatis/spring/boot/autoconfigure/MybatisAutoConfigurationTest.java
mybatis-spring-boot-autoconfigure/src/test/java/org/mybatis/spring/boot/autoconfigure/MybatisPropertiesTest.java
mybatis-spring-boot-samples/mybatis-spring-boot-sample-war/pom.xml
mybatis-spring-boot-samples/mybatis-spring-boot-sample-war/src/main/java/sample/mybatis/war/controller/CityRestController.java
mybatis-spring-boot-samples/mybatis-spring-boot-sample-web/src/main/java/sample/mybatis/web/controller/CityRestController.java

Fixes as follow:
* gh-732
* gh-733
* gh-735

Fixes gh-732 gh-733 gh-735

---

pom.xml

Compile with -parameters option

---

pom.xml

Change to use maven.compiler.parameters

---

pom.xml

Update to mybatis-spring 2.1.0 GA

---

mybatis-spring-boot-autoconfigure/src/main/resources/META-INF/spring.factories

Drop EnableAutoConfiguration from spring.factories

---

mybatis-spring-boot-samples/mybatis-spring-boot-sample-war/pom.xml

(cherry picked from commit a97ecdf3efa61a8de430d463463b2c1b2100b5a0)

Update dependency org.codehaus.cargo:cargo-maven3-plugin to v1.10.4

---

pom.xml

Apply MyBatis Spring 3.0.1-SNAPSHOT for supporting native image

---

pom.xml

Drop maven.compiler.parameters because apply the mybatis-parent 37

---

pom.xml

Update to Spring Boot 2.7.11

---

pom.xml

Update to MyBatis Spring 3.0.2-SNAPSHOT

---

pom.xml

Update to MyBatis Spring 2.1.1-SNAPSHOT

---

mybatis-spring-boot-autoconfigure/src/site/markdown/index.md
mybatis-spring-boot-autoconfigure/src/site/zh/markdown/index.md
mybatis-spring-boot-test-autoconfigure/src/site/markdown/index.md
mybatis-spring-boot-test-autoconfigure/src/site/zh/markdown/index.md

use implementation and testImplementation instead.

Gradle no longer supports compile and testCompile.

---

pom.xml

Upgrade to Spring Boot 2.7.12

---

mybatis-spring-boot-samples/mybatis-spring-boot-sample-xml/src/main/java/sample/mybatis/xml/mapper/CityMapper.java

As I understand, this sample is used for XML syntax. I don't know whether using annotation is on purpose?

Remove annotation syntax in XML sample

---

mybatis-spring-boot-samples/mybatis-spring-boot-sample-web/src/test/java/sample/mybatis/web/SampleMybatisWithMockBeanApplicationTest.java

Enhance integration test for `@MockBean`.
Related with mybatis/spring#865.

Add test with @MockBean

---

pom.xml

Update to MyBatis Spring 3.0.3-SNAPSHOT

---

.github/workflows/support.yaml

Enhance CI for samples. We support CI on Winfows.

Support samples CI with Windows

---

.github/workflows/support.yaml

(cherry picked from commit efe632c5020b052d69127c0424dbd2aa6bc53fb7)
* #900

Support samples CI with Windows on 2.3.x

---

pom.xml

Update dependency org.mybatis:mybatis to v3.5.14 on 2.3.x branch

---

mybatis-spring-boot-autoconfigure/src/main/java/org/mybatis/spring/boot/autoconfigure/MybatisProperties.java
mybatis-spring-boot-autoconfigure/src/test/java/org/mybatis/spring/boot/autoconfigure/MybatisPropertiesTest.java

https://github.com/mybatis/spring-boot-starter/issues/911

Support configuration databaseId.

---

pom.xml

Update spring-boot to v2.7.18

---

pom.xml

https://github.com/mybatis/spring/releases/tag/mybatis-spring-2.1.2

Update mybatis-spring to v2.1.2

---

README.md

update `README.md` Simplified Chinese Document link to resolve 404

[README] Update Document link zh to zh_CN

---

mybatis-spring-boot-samples/mybatis-spring-boot-sample-war/pom.xml

fix(deps): fix tomcat major version wrong

---

mybatis-spring-boot-autoconfigure/src/test/java/org/mybatis/spring/boot/autoconfigure/MybatisAutoConfigurationTest.java

Fix assertion message on testWithCheckConfigLocationFileDoesNotExists

---

mybatis-spring-boot-autoconfigure/src/test/java/org/mybatis/spring/boot/autoconfigure/MybatisAutoConfigurationTest.java

Polish assertion message on testWithCheckConfigLocationFileDoesNotExists
